from typing import Any, Protocol


class UoW(Protocol):
    def begin(self) -> None: ...

    async def flush(self) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...

    async def close(self) -> None: ...

    async def add(self, entity: Any) -> None: ...

    async def execute(self, stmt: Any) -> Any: ...
